parameters:
  solution: '**/Visio.sln'
  buildConfiguration: 'Release'
  webProject: '**/Visio.Web/Visio.Web.csproj'
  functionProject: '**/Visio.Recognition/Visio.Recognition.csproj'
  testProject: '**/Visio.Tests/Visio.Tests.csproj'

stages:
- stage: BuildAndTest
  displayName: Build & Test

  jobs:
  - job: BuildAndPackage
    displayName: 'Build Web & Function'
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        restoreSolution: '${{ parameters.solution }}'

    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: '${{ parameters.testProject }}'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --logger:trx'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/TestResults/*.trx'
        failTaskOnFailedTests: true

    # Build Web Project
    - task: DotNetCoreCLI@2
      displayName: 'Build Web Project'
      inputs:
        command: 'build'
        projects: '${{ parameters.webProject }}'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Output/WebApp'

    # Copy web.config
    - task: CopyFiles@2
      displayName: 'Copy web.config'
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/Visio.Web'
        contents: 'web.config'
        targetFolder: '$(Build.ArtifactStagingDirectory)/Output/WebApp'
    
    - task: CopyFiles@2
      displayName: 'Copy static'
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/Visio.Web/wwwroot'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/Output/WebApp/wwwroot'

    # List the contents of the WebApp folder for debugging
    - task: PowerShell@2
      displayName: 'List Contents of WebApp Folder'
      inputs:
        targetType: 'inline'
        script: 'Get-ChildItem -Recurse "$(Build.ArtifactStagingDirectory)/Output/WebApp"'
  
    # Archive Web App
    - task: ArchiveFiles@2
      displayName: 'Archive Web Zip'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Output/WebApp'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/publish-web.zip'
        includeRootFolder: false

    # Build Function Project
    - task: DotNetCoreCLI@2
      displayName: 'Build Function Project'
      inputs:
        command: 'build'
        projects: '${{ parameters.functionProject }}'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Output/FunctionApp'

    # Archive Function App
    - task: ArchiveFiles@2
      displayName: 'Archive Function Zip'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Output/FunctionApp'
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/publish-func.zip'
        includeRootFolder: false

    # Publish Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Web Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/publish-web.zip'
        artifactName: 'web-drop'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Function Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/publish-func.zip'
        artifactName: 'function-drop'
