name: $(Date:dd-MM-yyyy).$(Rev:r)

trigger:
  - none

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'

stages:
- template:  templates/build-packages-from-git.yml

- template: templates/approve.yml
  parameters:
    environment: dev

- template: templates/deployment-webapp.yml
  parameters:
    variable_group: 'visio_variable_group'
    stage_name: Deploy_Dev
    environment: 'dev'

# - template: templates/approve.yml
#   parameters:
#     environment: qa

# - template: templates/deployment-webapp.yml
#   parameters:
#     variable_group: 'visio_variable_group'
#     environment: 'qa'